version: '3.7'

services:
  server:
    image: gitea/gitea:1.13.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
#    volumes:
#      - ./gitea:/data
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "8822:22"
    networks:
      gitea:
       ipv4_address: 172.30.0.5
      
networks:
  gitea:
   name: gitea
   ipam:
     driver: default
     config:
       - subnet: "172.30.0.0/24"
